version: '3.8'
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
  metadata:
    build:
      context: ./metadata
    ports:
      - 8081:8081
    depends_on:
      - db
  rating:
    build:
      context: ./rating
    ports:
      - 8082:8082
    depends_on:
      - db
  movie:
    build:
      context: ./movie
    ports:
      - 8083:8083
    depends_on:
      - db